In [16]:
print(5+3)

"""results = pd.read_csv(r'C:\Users\yd26114\Desktop\fc\Tables\All_Races_Results_Info.csv')
race_generic_info = pd.read_csv(r'C:\Users\yd26114\Desktop\fc\Tables\All_Races_Generic_Info.csv')
"""
"""
stages_results_1 = pd.read_csv(r"C:\Users\yd26114\Desktop\fc\Tables\All_Stages_Results_0_to_1000.csv")
stages_results_2 = pd.read_csv(r"C:\Users\yd26114\Desktop\fc\Tables\All_Stages_Results_1000_to_2000.csv")
stages_results_3 = pd.read_csv(r"C:\Users\yd26114\Desktop\fc\Tables\All_Stages_Results_2000_to_4000.csv")
stages_results_4 = pd.read_csv(r"C:\Users\yd26114\Desktop\fc\Tables\All_Stages_Results_3000_to_4000.csv")
stages_results_5 = pd.read_csv(r"C:\Users\yd26114\Desktop\fc\Tables\All_Stages_Results_4000_to_4347.csv")
"""

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 26-27: truncated \UXXXXXXXX escape (Temp/ipykernel_11452/3370465430.py, line 5)

In [5]:
display(results.head())
display(race_generic_info.head())

,Unnamed: 0,Pos,Rider,Born,Team,Time,Time in Seconds,Gap in Seconds,Percentage of Winning Time,Race,Year,Gender,Category,Race Code,Rider Code,Team Code,UCI,Unnamed: 17
0,0,01,O'Grady Stuart,1973,Crédit Agricole,04:10:29,15029,0,1.0,Melbourne to Sorrento,2000,Men,1.5,886,15.0,753,NaN,NaN
1,1,02,Drew Jamie,1973,Mercury Cycling Team,+ 00,15029,0,1.0,Melbourne to Sorrento,2000,Men,1.5,886,5936.0,1232,NaN,NaN
2,2,03,Rogers Michael,1979,Mapei - Quick Step,+ 00,15029,0,1.0,Melbourne to Sorrento,2000,Men,1.5,886,13.0,568,NaN,NaN
3,3,04,Hall Jonathan,1972,Festina - Lotus,+ 00,15029,0,1.0,Melbourne to Sorrento,2000,Men,1.5,886,1519.0,491,NaN,NaN
4,4,05,Hughes Cameron,1972,-,+ 00,15029,0,1.0,Melbourne to Sorrento,2000,Men,1.5,886,13850.0,0,NaN,NaN

NameError: name 'race_generic_info' is not defined